 syntax="proto3";
 package
// metamodel_version: 1.11.0
// version: 1.1-rc2
message ActionType
 {
 repeated  fieldType field = 0
 repeated  fieldRefType fieldRef = 0
 repeated  componentType component = 0
 repeated  componentRefType componentRef = 0
 repeated  groupRefType groupRef = 0
 repeated  messageRefType messageRef = 0
 repeated  triggerType trigger = 0
 repeated  timerSchedule timerSchedule = 0
 repeated  groupType group = 0
 repeated  expressionType assign = 0
 }
// Participants and the message flows between them
message Actors
 {
 repeated  actorType actor = 0
 repeated  flowType flow = 0
  annotation annotation = 0
  string base = 0
 }
// Represents a class of participants
message ActorType
 {
 repeated  fieldType field = 0
 repeated  fieldRefType fieldRef = 0
 repeated  componentType component = 0
 repeated  componentRefType componentRef = 0
 repeated  groupRefType groupRef = 0
 repeated  stateMachineType states = 0
 repeated  timerType timer = 0
 repeated  groupType group = 0
  annotation annotation = 0
  name name = 0
 }
message Annotation
 {
 repeated  documentation documentation = 0
 repeated  appinfo appinfo = 0
  version added = 0
  eP addedEp = 0
  changeType changeType = 0
  eP deprecatedEp = 0
  string issue = 0
  version lastModified = 0
  version replaced = 0
  eP replacedEp = 0
  id replacedByField = 0
  supportType supported = 0
  version updated = 0
  eP updatedEp = 0
  version deprecated = 0
 }
// Usage specific annotation, optionally with link to an external reference or standard
message Appinfo
 {
  uri specUrl = 0
  string value = 0
 repeated  string content = 0
 repeated  string extraAttributes = 0
  language langId = 0
  purpose purpose = 0
  version added = 0
  eP addedEp = 0
  changeType changeType = 0
  eP deprecatedEp = 0
  string issue = 0
  version lastModified = 0
  version replaced = 0
  eP replacedEp = 0
  id replacedByField = 0
  supportType supported = 0
  version updated = 0
  eP updatedEp = 0
  version deprecated = 0
 }
message BlockAssignmentType
 {
 repeated  componentRefType componentRef = 0
 repeated  groupRefType groupRef = 0
 repeated  fieldRefType fieldRef = 0
 }
message Categories
 {
 repeated  categoryType category = 0
  annotation annotation = 0
  string base = 0
 }
message CategoryType
 {
  name fixmlFileName = 0
  catComponentType componentType = 0
  catIncludeFile includeFile = 0
  annotation annotation = 0
  name name = 0
  name section = 0
  version added = 0
  eP addedEp = 0
  changeType changeType = 0
  eP deprecatedEp = 0
  string issue = 0
  version lastModified = 0
  version replaced = 0
  eP replacedEp = 0
  id replacedByField = 0
  supportType supported = 0
  version updated = 0
  eP updatedEp = 0
  version deprecated = 0
 }
message CodeSets
 {
 repeated  codeSetType codeSet = 0
  annotation annotation = 0
  string base = 0
 }
message CodeSetType
 {
 repeated  codeType code = 0
  string default = 0
  uri specUrl = 0
  unionDataType unionDataType = 0
  annotation annotation = 0
  name type = 0
  name abbrName = 0
  id scenarioId = 0
  id id = 0
  name name = 0
  name scenario = 0
  id scenarioRefId = 0
  name scenarioRef = 0
  version added = 0
  eP addedEp = 0
  changeType changeType = 0
  eP deprecatedEp = 0
  string issue = 0
  version lastModified = 0
  version replaced = 0
  eP replacedEp = 0
  id replacedByField = 0
  supportType supported = 0
  version updated = 0
  eP updatedEp = 0
  version deprecated = 0
 }
message CodeType
 {
  string value = 0
  integer sort = 0
  annotation annotation = 0
  string group = 0
  name abbrName = 0
  id scenarioId = 0
  id id = 0
  name name = 0
  name scenario = 0
  version added = 0
  eP addedEp = 0
  changeType changeType = 0
  eP deprecatedEp = 0
  string issue = 0
  version lastModified = 0
  version replaced = 0
  eP replacedEp = 0
  id replacedByField = 0
  supportType supported = 0
  version updated = 0
  eP updatedEp = 0
  version deprecated = 0
 }
message ComponentRefType
 {
 repeated  blockAssignmentType blockAssignment = 0
  presence presence = 0
 repeated  componentRuleType rule = 0
  annotation annotation = 0
  componentName instanceName = 0
  id scenarioId = 0
  id id = 0
  name name = 0
  name scenario = 0
  version added = 0
  eP addedEp = 0
  changeType changeType = 0
  eP deprecatedEp = 0
  string issue = 0
  version lastModified = 0
  version replaced = 0
  eP replacedEp = 0
  id replacedByField = 0
  supportType supported = 0
  version updated = 0
  eP updatedEp = 0
  version deprecated = 0
 }
message ComponentRuleType
 {
  expressionType when = 0
  presence presence = 0
  name name = 0
 }
message Components
 {
 repeated  componentType component = 0
  annotation annotation = 0
  string base = 0
 }
message ComponentType
 {
 repeated  componentRefType componentRef = 0
 repeated  groupRefType groupRef = 0
 repeated  fieldRefType fieldRef = 0
  string rendering = 0
  memberType which = 0
  annotation annotation = 0
  name category = 0
  version added = 0
  eP addedEp = 0
  changeType changeType = 0
  eP deprecatedEp = 0
  string issue = 0
  version lastModified = 0
  version replaced = 0
  eP replacedEp = 0
  id replacedByField = 0
  supportType supported = 0
  version updated = 0
  eP updatedEp = 0
  version deprecated = 0
  name abbrName = 0
  id scenarioId = 0
  id id = 0
  name name = 0
  name scenario = 0
  id scenarioRefId = 0
  name scenarioRef = 0
 }
message Concepts
 {
 repeated  conceptType concept = 0
  annotation annotation = 0
  string base = 0
 }
message ConceptType
 {
 repeated  componentRefType componentRef = 0
 repeated  groupRefType groupRef = 0
 repeated  fieldRefType fieldRef = 0
 repeated  messageRefType messageRef = 0
  annotation annotation = 0
  name name = 0
 }
message Datatype
 {
 repeated  mappedDatatype mappedDatatype = 0
  id scenarioId = 0
  name baseType = 0
  annotation annotation = 0
  name name = 0
  name scenario = 0
  version added = 0
  eP addedEp = 0
  changeType changeType = 0
  eP deprecatedEp = 0
  string issue = 0
  version lastModified = 0
  version replaced = 0
  eP replacedEp = 0
  id replacedByField = 0
  supportType supported = 0
  version updated = 0
  eP updatedEp = 0
  version deprecated = 0
 }
message Datatypes
 {
 repeated  datatype datatype = 0
  annotation annotation = 0
  string base = 0
 }
message DcContributor
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DcCoverage
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DcCreator
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DcDate
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DcDescription
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
// This complexType is included as a convenience for schema authors who need to define a root or container element for all of the DC elements.
message DcElementContainer
 {
  string title = 0
  string creator = 0
  string subject = 0
  string description = 0
  string publisher = 0
  string contributor = 0
  string date = 0
  string format = 0
  string source = 0
  string language = 0
  string relation = 0
  string coverage = 0
  string rights = 0
  string alternative = 0
  string tableOfContents = 0
  string abstract = 0
  string created = 0
  string valid = 0
  string available = 0
  string issued = 0
  string modified = 0
  string dateAccepted = 0
  string dateCopyrighted = 0
  string dateSubmitted = 0
  string extent = 0
  string medium = 0
  string isVersionOf = 0
  string hasVersion = 0
  string isReplacedBy = 0
  string replaces = 0
  string isRequiredBy = 0
  string requires = 0
  string isPartOf = 0
  string hasPart = 0
  string isReferencedBy = 0
  string references = 0
  string isFormatOf = 0
  string hasFormat = 0
  string conformsTo = 0
  string spatial = 0
  string temporal = 0
  string audience = 0
  string accrualMethod = 0
  string accrualPeriodicity = 0
  string accrualPolicy = 0
  string instructionalMethod = 0
  string provenance = 0
  string rightsHolder = 0
  string mediator = 0
  string educationLevel = 0
  string accessRights = 0
  string license = 0
  string bibliographicCitation = 0
  string type = 0
  string identifier = 0
 }
message DcFormat
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DcIdentifier
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DcLanguage
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DcPublisher
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DcRelation
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DcRights
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
// This is the default type for all of the DC elements. It permits text content only with optional xml:lang attribute. Text is allowed because mixed="true", but sub-elements are disallowed because minOccurs="0" and maxOccurs="0" are on the xs:any tag. This complexType allows for restriction or extension permitting child elements.
message DcSimpleLiteral
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DcSource
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DcSubject
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsAbstract
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsAccessRights
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsAccrualMethod
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsAccrualPeriodicity
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsAccrualPolicy
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsAlternative
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsAudience
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsAvailable
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsBibliographicCitation
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsBox
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsConformsTo
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsContributor
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsCoverage
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsCreated
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsCreator
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsDate
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsDateAccepted
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsDateCopyrighted
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsDateSubmitted
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsDCMIType
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsDDC
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsDescription
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsEducationLevel
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
// This is included as a convenience for schema authors who need to define a root or container element for all of the DC elements and element refinements.
message DctermsElementOrRefinementContainer
 {
  string title = 0
  string creator = 0
  string subject = 0
  string description = 0
  string publisher = 0
  string contributor = 0
  string date = 0
  string format = 0
  string source = 0
  string language = 0
  string relation = 0
  string coverage = 0
  string rights = 0
  string alternative = 0
  string tableOfContents = 0
  string abstract = 0
  string created = 0
  string valid = 0
  string available = 0
  string issued = 0
  string modified = 0
  string dateAccepted = 0
  string dateCopyrighted = 0
  string dateSubmitted = 0
  string extent = 0
  string medium = 0
  string isVersionOf = 0
  string hasVersion = 0
  string isReplacedBy = 0
  string replaces = 0
  string isRequiredBy = 0
  string requires = 0
  string isPartOf = 0
  string hasPart = 0
  string isReferencedBy = 0
  string references = 0
  string isFormatOf = 0
  string hasFormat = 0
  string conformsTo = 0
  string spatial = 0
  string temporal = 0
  string audience = 0
  string accrualMethod = 0
  string accrualPeriodicity = 0
  string accrualPolicy = 0
  string instructionalMethod = 0
  string provenance = 0
  string rightsHolder = 0
  string mediator = 0
  string educationLevel = 0
  string accessRights = 0
  string license = 0
  string bibliographicCitation = 0
  string type = 0
  string identifier = 0
 }
message DctermsExtent
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsFormat
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsHasFormat
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsHasPart
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsHasVersion
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsIdentifier
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsIMT
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsInstructionalMethod
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsIsFormatOf
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsISO3166
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsISO6392
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsISO6393
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsIsPartOf
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsIsReferencedBy
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsIsReplacedBy
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsIsRequiredBy
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsIssued
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsIsVersionOf
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsLanguage
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsLCC
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsLCSH
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsLicense
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsMediator
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsMedium
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsMESH
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsModified
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsPeriod
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsPoint
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsProvenance
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsPublisher
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsReferences
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsRelation
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsReplaces
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsRequires
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsRFC1766
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsRFC3066
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsRFC4646
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsRights
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsRightsHolder
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsSource
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsSpatial
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsSubject
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsTableOfContents
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsTemporal
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsTGN
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsTitle
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsType
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsUDC
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsURI
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsValid
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DctermsW3CDTF
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DcTitle
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message DcType
 {
  string value = 0
 repeated  string content = 0
  string lang = 0
 }
message Documentation
 {
  string value = 0
 repeated  string content = 0
  language langId = 0
  purpose purpose = 0
  mime contentType = 0
  version added = 0
  eP addedEp = 0
  changeType changeType = 0
  eP deprecatedEp = 0
  string issue = 0
  version lastModified = 0
  version replaced = 0
  eP replacedEp = 0
  id replacedByField = 0
  supportType supported = 0
  version updated = 0
  eP updatedEp = 0
  version deprecated = 0
 }
message EncodingType
 {
  datetime activationTime = 0
  datetime deactivationTime = 0
  layer layer = 0
  uri orchestration = 0
 repeated  string extraAttributes = 0
  interfaceAnnotation annotation = 0
  protocolName name = 0
  string version = 0
  datetime deprecated = 0
  interfaceReliability reliability = 0
 }
message ExtensionInline
 {
 repeated  string content = 0
 }
message FieldRefType
 {
  id lengthId = 0
  id nonEncodedFieldId = 0
 repeated  fieldRuleType rule = 0
  expressionType assign = 0
  annotation annotation = 0
  name instanceName = 0
  id scenarioId = 0
  id id = 0
  name name = 0
  name scenario = 0
  version added = 0
  eP addedEp = 0
  changeType changeType = 0
  eP deprecatedEp = 0
  string issue = 0
  version lastModified = 0
  version replaced = 0
  eP replacedEp = 0
  id replacedByField = 0
  supportType supported = 0
  version updated = 0
  eP updatedEp = 0
  version deprecated = 0
  string minInclusive = 0
  string maxInclusive = 0
  integer implLength = 0
  integer implMinLength = 0
  integer implMaxLength = 0
  presence presence = 0
  string value = 0
  string rendering = 0
  string encoding = 0
 }
message FieldRuleType
 {
  uniqueInline unique = 0
  expressionType when = 0
 repeated  expressionType assign = 0
  name name = 0
  name type = 0
  string minInclusive = 0
  string maxInclusive = 0
  integer implLength = 0
  integer implMinLength = 0
  integer implMaxLength = 0
  presence presence = 0
  string value = 0
  string rendering = 0
  string encoding = 0
 }
message Fields
 {
 repeated  fieldType field = 0
  annotation annotation = 0
  string base = 0
 }
message FieldType
 {
  id lengthId = 0
  id nonEncodedFieldId = 0
  id discriminatorId = 0
  name baseCategory = 0
  name baseCategoryAbbrName = 0
  unionDataType unionDataType = 0
 repeated  fieldRuleType rule = 0
  expressionType assign = 0
  annotation annotation = 0
  name type = 0
  name codeSet = 0
  name abbrName = 0
  id scenarioId = 0
  id id = 0
  name name = 0
  name scenario = 0
  version added = 0
  eP addedEp = 0
  changeType changeType = 0
  eP deprecatedEp = 0
  string issue = 0
  version lastModified = 0
  version replaced = 0
  eP replacedEp = 0
  id replacedByField = 0
  supportType supported = 0
  version updated = 0
  eP updatedEp = 0
  version deprecated = 0
  string minInclusive = 0
  string maxInclusive = 0
  integer implLength = 0
  integer implMinLength = 0
  integer implMaxLength = 0
  presence presence = 0
  string value = 0
  string rendering = 0
  string encoding = 0
 }
// A stream of messages in one direction
message FlowType
 {
  string source = 0
  string destination = 0
  annotation annotation = 0
  name name = 0
  reliability reliability = 0
 }
message GroupRefType
 {
 repeated  blockAssignmentType blockAssignment = 0
  presence presence = 0
 repeated  componentRuleType rule = 0
  annotation annotation = 0
  componentName instanceName = 0
  id scenarioId = 0
  id id = 0
  name name = 0
  name scenario = 0
  version added = 0
  eP addedEp = 0
  changeType changeType = 0
  eP deprecatedEp = 0
  string issue = 0
  version lastModified = 0
  version replaced = 0
  eP replacedEp = 0
  id replacedByField = 0
  supportType supported = 0
  version updated = 0
  eP updatedEp = 0
  version deprecated = 0
  integer implMinOccurs = 0
  unboundedIntType implMaxOccurs = 0
 }
message Groups
 {
 repeated  groupType group = 0
  annotation annotation = 0
  string base = 0
 }
// A repeating group. Logically, groupType is a subclass of componentType, but to make numInGroup first in the sequence, it cannot be an extension.
message GroupType
 {
  fieldRefType numInGroup = 0
 repeated  componentRefType componentRef = 0
 repeated  groupRefType groupRef = 0
 repeated  fieldRefType fieldRef = 0
  string rendering = 0
  integer implMinOccurs = 0
  unboundedIntType implMaxOccurs = 0
  memberType which = 0
  annotation annotation = 0
  name category = 0
  version added = 0
  eP addedEp = 0
  changeType changeType = 0
  eP deprecatedEp = 0
  string issue = 0
  version lastModified = 0
  version replaced = 0
  eP replacedEp = 0
  id replacedByField = 0
  supportType supported = 0
  version updated = 0
  eP updatedEp = 0
  version deprecated = 0
  name abbrName = 0
  id scenarioId = 0
  id id = 0
  name name = 0
  name scenario = 0
  id scenarioRefId = 0
  name scenarioRef = 0
 }
message IdentifiersType
 {
 repeated  identifierType correlate = 0
 repeated  identifierType assign = 0
  annotation annotation = 0
 }
message IdentifierType
 {
  string value = 0
  string name = 0
 }
message InterfaceAnnotation
 {
 repeated  interfaceDocumentation documentation = 0
 repeated  interfaceAppinfo appinfo = 0
 }
// Usage specific annotation, optionally with link to an external reference or standard
message InterfaceAppinfo
 {
  uri specUrl = 0
  string value = 0
 repeated  string content = 0
 repeated  string extraAttributes = 0
  string langId = 0
  interfacePurpose purpose = 0
 }
message InterfaceDocumentation
 {
  string value = 0
 repeated  string content = 0
  string langId = 0
  interfacePurpose purpose = 0
  string contentType = 0
 }
// This represents the current state of service and session configurations. Changes to configuration can represented with patch operations. See IETF RFC 5261
message Interfaces
 {
  dctermsElementOrRefinementContainer metadata = 0
 repeated  interfaceType interface = 0
 }
message InterfaceType
 {
 repeated  serviceType service = 0
 repeated  userInterfaceType userInterface = 0
 repeated  sessionProtocolType sessionProtocol = 0
 repeated  protocolType protocol = 0
 repeated  transportProtocolType transport = 0
 repeated  string extraAttributes = 0
 repeated  encodingType encoding = 0
  interfaceAnnotation annotation = 0
  string name = 0
  sessionsInline sessions = 0
 }
message MappedDatatype
 {
  extensionInline extension = 0
  datatypeStandard standard = 0
  boolean builtin = 0
  string pattern = 0
  string element = 0
  integer size = 0
  string parameter = 0
  string minInclusive = 0
  string maxInclusive = 0
  annotation annotation = 0
  string base = 0
 }
message MessageRefType
 {
  identifiersType identifiers = 0
  msgType msgType = 0
  integer implMinOccurs = 0
  unboundedIntType implMaxOccurs = 0
  id scenarioId = 0
  id id = 0
  name name = 0
  name scenario = 0
 }
message Messages
 {
 repeated  messageType message = 0
  annotation annotation = 0
  string base = 0
 }
message MessageType
 {
  structureInline structure = 0
  expressionType when = 0
  responsesInline responses = 0
  msgType msgType = 0
  string rendering = 0
  annotation annotation = 0
  name category = 0
  name flow = 0
  name abbrName = 0
  id scenarioId = 0
  id id = 0
  name name = 0
  name scenario = 0
  id scenarioRefId = 0
  name scenarioRef = 0
  version added = 0
  eP addedEp = 0
  changeType changeType = 0
  eP deprecatedEp = 0
  string issue = 0
  version lastModified = 0
  version replaced = 0
  eP replacedEp = 0
  id replacedByField = 0
  supportType supported = 0
  version updated = 0
  eP updatedEp = 0
  version deprecated = 0
 }
message ProtocolType
 {
  datetime activationTime = 0
  datetime deactivationTime = 0
  layer layer = 0
  uri orchestration = 0
 repeated  string extraAttributes = 0
  interfaceAnnotation annotation = 0
  protocolName name = 0
  string version = 0
  datetime deprecated = 0
  interfaceReliability reliability = 0
 }
message Repository
 {
  dctermsElementOrRefinementContainer metadata = 0
  categories categories = 0
  sections sections = 0
  datatypes datatypes = 0
  codeSets codeSets = 0
  fields fields = 0
  actors actors = 0
  components components = 0
  groups groups = 0
  messages messages = 0
  concepts concepts = 0
  scenarios scenarios = 0
  string guid = 0
  uri specUrl = 0
  uri namespace = 0
  string expressionLanguage = 0
  annotation annotation = 0
  string name = 0
  version version = 0
 }
message ResponsesInline
 {
 repeated  responseType response = 0
 }
// Any number of action behaviors can be triggered by the same 'when' condition
message ResponseType
 {
 repeated  fieldType field = 0
 repeated  fieldRefType fieldRef = 0
 repeated  componentType component = 0
 repeated  componentRefType componentRef = 0
 repeated  groupRefType groupRef = 0
 repeated  messageRefType messageRef = 0
 repeated  triggerType trigger = 0
 repeated  timerSchedule timerSchedule = 0
 repeated  groupType group = 0
 repeated  expressionType assign = 0
  expressionType when = 0
  synchronization sync = 0
  annotation annotation = 0
  name name = 0
 }
// The default scenario is id='1' name='base'.
message Scenarios
 {
 repeated  scenarioType scenario = 0
  annotation annotation = 0
  string base = 0
 }
// The use case of an element, distinguished by workflow, asset class, etc.
message ScenarioType
 {
  annotation annotation = 0
  id id = 0
  name name = 0
 }
message Sections
 {
 repeated  sectionType section = 0
  annotation annotation = 0
  string base = 0
 }
message SectionType
 {
  integer displayOrder = 0
  name fixmlFileName = 0
  annotation annotation = 0
  name name = 0
  version added = 0
  eP addedEp = 0
  changeType changeType = 0
  eP deprecatedEp = 0
  string issue = 0
  version lastModified = 0
  version replaced = 0
  eP replacedEp = 0
  id replacedByField = 0
  supportType supported = 0
  version updated = 0
  eP updatedEp = 0
  version deprecated = 0
 }
message ServiceType
 {
  datetime activationTime = 0
  datetime deactivationTime = 0
  layer layer = 0
  uri orchestration = 0
 repeated  string extraAttributes = 0
  interfaceAnnotation annotation = 0
  protocolName name = 0
  string version = 0
  datetime deprecated = 0
  interfaceReliability reliability = 0
 }
message SessionProtocolType
 {
  datetime activationTime = 0
  datetime deactivationTime = 0
  layer layer = 0
  uri orchestration = 0
 repeated  string extraAttributes = 0
  interfaceAnnotation annotation = 0
  protocolName name = 0
  string version = 0
  datetime deprecated = 0
  interfaceReliability reliability = 0
 }
message SessionsInline
 {
 repeated  sessionType session = 0
 }
message SessionType
 {
 repeated  serviceType service = 0
 repeated  userInterfaceType userInterface = 0
 repeated  sessionProtocolType sessionProtocol = 0
 repeated  protocolType protocol = 0
 repeated  transportProtocolType transport = 0
 repeated  string extraAttributes = 0
 repeated  encodingType encoding = 0
  interfaceAnnotation annotation = 0
  string name = 0
  role role = 0
  string securityKeys = 0
  datetime activationTime = 0
  datetime deactivationTime = 0
 repeated  identifierType identifier = 0
 }
message StateMachineType
 {
  stateType initial = 0
 repeated  stateType state = 0
  annotation annotation = 0
  name name = 0
 }
// A state of a state machine. If it has no transitions, then it is a final state.
message StateType
 {
 repeated  transitionType transition = 0
  actionType onentry = 0
  actionType activity = 0
  actionType onexit = 0
  annotation annotation = 0
  name name = 0
 }
message StructureInline
 {
 repeated  componentRefType componentRef = 0
 repeated  groupRefType groupRef = 0
 repeated  fieldRefType fieldRef = 0
  memberType which = 0
 }
message TimerSchedule
 {
  actionType activity = 0
  timerOperation operation = 0
  string interval = 0
  name actor = 0
  name name = 0
 }
message TimerType
 {
  name name = 0
 }
message TransitionType
 {
  expressionType when = 0
  string target = 0
  annotation annotation = 0
  name name = 0
 }
message TransportProtocolType
 {
  datetime activationTime = 0
  datetime deactivationTime = 0
  layer layer = 0
  uri orchestration = 0
  interfaceAnnotation annotation = 0
  protocolName name = 0
  string version = 0
  datetime deprecated = 0
  interfaceReliability reliability = 0
  string address = 0
  messageCast messageCast = 0
  transportUse use = 0
 repeated  string extraAttributes = 0
 }
message TriggerType
 {
  string stateMachine = 0
  name actor = 0
  name name = 0
 }
message UniqueInline
 {
 repeated  fieldRefType fieldRef = 0
 }
message UserInterfaceType
 {
  datetime activationTime = 0
  datetime deactivationTime = 0
  layer layer = 0
  uri orchestration = 0
 repeated  string extraAttributes = 0
  interfaceAnnotation annotation = 0
  protocolName name = 0
  string version = 0
  datetime deprecated = 0
  interfaceReliability reliability = 0
 }
// Container for the global <xs:attribute> declarations defined in xml.xsd. Each attribute here is referenceable from other XSDs via ``ref="xml:<name>"``.
message XmlGlobalAttributes
 {
  xmlLangType lang = 0
  xmlSpaceType space = 0
  uri base = 0
  string id = 0
 }
